/*
 *----------------------------------------------------------------------
 *    UCT T-Kernel 2.0 DevKit tuned
 *
 *    Copyright (c) 2013 UC Technology. All Rights Reserved.
 *----------------------------------------------------------------------
 *
 *    Version:   2.00.00
 *    Released by UC Technology (http://www.uctec.com/) at 2013/06/14.
 *
 *----------------------------------------------------------------------
 */

/*
 *	Not Supported T-Kernel system call
 *
 *	To select not support system call,
 *	remark "USE_FUNC_TD_XXX_YYY" macro in "config/tk_config_func.h"
 *
 */

#ifndef	USE_FUNC_TD_LST_TSK
__td_lst_tsk:
#endif

#ifndef	USE_FUNC_TD_LST_SEM
__td_lst_sem:
#endif

#ifndef	USE_FUNC_TD_LST_FLG
__td_lst_flg:
#endif

#ifndef	USE_FUNC_TD_LST_MBX
__td_lst_mbx:
#endif

#ifndef	USE_FUNC_TD_LST_MTX
__td_lst_mtx:
#endif

#ifndef	USE_FUNC_TD_LST_MBF
__td_lst_mbf:
#endif

#ifndef	USE_FUNC_TD_LST_POR
__td_lst_por:
#endif

#ifndef	USE_FUNC_TD_LST_MPF
__td_lst_mpf:
#endif

#ifndef	USE_FUNC_TD_LST_MPL
__td_lst_mpl:
#endif

#ifndef	USE_FUNC_TD_LST_CYC
__td_lst_cyc:
#endif

#ifndef	USE_FUNC_TD_LST_ALM
__td_lst_alm:
#endif

#ifndef	USE_FUNC_TD_LST_SSY
__td_lst_ssy:
#endif

#ifndef	USE_FUNC_TD_REF_SEM
__td_ref_sem:
#endif

#ifndef	USE_FUNC_TD_REF_FLG
__td_ref_flg:
#endif

#ifndef	USE_FUNC_TD_REF_MBX
__td_ref_mbx:
#endif

#ifndef	USE_FUNC_TD_REF_MTX
__td_ref_mtx:
#endif

#ifndef	USE_FUNC_TD_REF_MBF
__td_ref_mbf:
#endif

#ifndef	USE_FUNC_TD_REF_POR
__td_ref_por:
#endif

#ifndef	USE_FUNC_TD_REF_MPF
__td_ref_mpf:
#endif

#ifndef	USE_FUNC_TD_REF_MPL
__td_ref_mpl:
#endif

#ifndef	USE_FUNC_TD_REF_CYC
__td_ref_cyc:
__td_ref_cyc_u:
#endif

#ifndef	USE_FUNC_TD_REF_ALM
__td_ref_alm:
__td_ref_alm_u:
#endif

#ifndef	USE_FUNC_TD_REF_SSY
__td_ref_ssy:
#endif

#ifndef	USE_FUNC_TD_REF_TSK
__td_ref_tsk:
__td_ref_tsk_u:
#endif

#ifndef	USE_FUNC_TD_REF_TEX
__td_ref_tex:
#endif

#ifndef	USE_FUNC_TD_INF_TSK
__td_inf_tsk:
__td_inf_tsk_u:
#endif

#ifndef	USE_FUNC_TD_GET_REG
__td_get_reg:
#endif

#ifndef	USE_FUNC_TD_SET_REG
__td_set_reg:
#endif

#ifndef	USE_FUNC_TD_REF_SYS
__td_ref_sys:
#endif

#ifndef	USE_FUNC_TD_GET_TIM
__td_get_tim:
__td_get_tim_u:
#endif

#ifndef	USE_FUNC_TD_GET_OTM
__td_get_otm:
__td_get_otm_u:
#endif

#ifndef	USE_FUNC_TD_RDY_QUE
__td_rdy_que:
#endif

#ifndef	USE_FUNC_TD_SEM_QUE
__td_sem_que:
#endif

#ifndef	USE_FUNC_TD_FLG_QUE
__td_flg_que:
#endif

#ifndef	USE_FUNC_TD_MBX_QUE
__td_mbx_que:
#endif

#ifndef	USE_FUNC_TD_MTX_QUE
__td_mtx_que:
#endif

#ifndef	USE_FUNC_TD_SMBF_QUE
__td_smbf_que:
#endif

#ifndef	USE_FUNC_TD_RMBF_QUE
__td_rmbf_que:
#endif

#ifndef	USE_FUNC_TD_CAL_QUE
__td_cal_que:
#endif

#ifndef	USE_FUNC_TD_ACP_QUE
__td_acp_que:
#endif

#ifndef	USE_FUNC_TD_MPF_QUE
__td_mpf_que:
#endif

#ifndef	USE_FUNC_TD_MPL_QUE
__td_mpl_que:
#endif

#ifndef	USE_FUNC_TD_HOK_SVC
__td_hok_svc:
#endif

#ifndef	USE_FUNC_TD_HOK_DSP
__td_hok_dsp:
#endif

#ifndef	USE_FUNC_TD_HOK_INT
__td_hok_int:
#endif

#ifndef	USE_FUNC_TD_REF_DSNAME
__td_ref_dsname:
#endif

#ifndef	USE_FUNC_TD_SET_DSNAME
__td_set_dsname:
#endif

