/*
 *----------------------------------------------------------------------
 *    UCT T-Kernel 2.0 DevKit tuned
 *
 *    Copyright (c) 2013 UC Technology. All Rights Reserved.
 *----------------------------------------------------------------------
 *
 *    Version:   2.00.00
 *    Released by UC Technology (http://www.uctec.com/) at 2013/06/14.
 *
 *----------------------------------------------------------------------
 */

/*
 *	Not Supported T-Kernel system call
 *
 *	To select not support system call,
 *	remark "USE_FUNC_TK_XXX_YYY" macro in "config/tk_config_func.h"
 *
 */

#ifndef	USE_FUNC_TK_CRE_TSK
__tk_cre_tsk:
#endif

#ifndef	USE_FUNC_TK_DEL_TSK
__tk_del_tsk:
#endif

#ifndef	USE_FUNC_TK_STA_TSK
__tk_sta_tsk:
#endif

#ifndef	USE_FUNC_TK_EXT_TSK
__tk_ext_tsk:
#endif

#ifndef	USE_FUNC_TK_EXD_TSK
__tk_exd_tsk:
#endif

#ifndef	USE_FUNC_TK_TER_TSK
__tk_ter_tsk:
#endif

#ifndef	USE_FUNC_TK_DIS_DSP
__tk_dis_dsp:
#endif

#ifndef	USE_FUNC_TK_ENA_DSP
__tk_ena_dsp:
#endif

#ifndef	USE_FUNC_TK_CHG_PRI
__tk_chg_pri:
#endif

#ifndef	USE_FUNC_TK_CHG_SLT
__tk_chg_slt:
__tk_chg_slt_u:
#endif

#ifndef	USE_FUNC_TK_ROT_RDQ
__tk_rot_rdq:
#endif

#ifndef	USE_FUNC_TK_REL_WAI
__tk_rel_wai:
#endif

#ifndef	USE_FUNC_TK_GET_TID
__tk_get_tid:
#endif

#ifndef	USE_FUNC_TK_GET_TSP
__tk_get_tsp:
#endif

#ifndef	USE_FUNC_TK_SET_TSP
__tk_set_tsp:
#endif

#ifndef	USE_FUNC_TK_GET_RID
__tk_get_rid:
#endif

#ifndef	USE_FUNC_TK_SET_RID
__tk_set_rid:
#endif

#ifndef	USE_FUNC_TK_GET_REG
__tk_get_reg:
#endif

#ifndef	USE_FUNC_TK_SET_REG
__tk_set_reg:
#endif

#ifndef	USE_FUNC_TK_GET_CPR
__tk_get_cpr:
#endif

#ifndef	USE_FUNC_TK_SET_CPR
__tk_set_cpr:
#endif

#ifndef	USE_FUNC_TK_INF_TSK
__tk_inf_tsk:
__tk_inf_tsk_u:
#endif

#ifndef	USE_FUNC_TK_REF_TSK
__tk_ref_tsk:
__tk_ref_tsk_u:
#endif

#ifndef	USE_FUNC_TK_DEF_TEX
__tk_def_tex:
#endif

#ifndef	USE_FUNC_TK_ENA_TEX
__tk_ena_tex:
#endif

#ifndef	USE_FUNC_TK_DIS_TEX
__tk_dis_tex:
#endif

#ifndef	USE_FUNC_TK_RAS_TEX
__tk_ras_tex:
#endif

#ifndef	USE_FUNC_TK_END_TEX
__tk_end_tex:
#endif

#ifndef	USE_FUNC_TK_REF_TEX
__tk_ref_tex:
#endif

#ifndef	USE_FUNC_TK_SUS_TSK
__tk_sus_tsk:
#endif

#ifndef	USE_FUNC_TK_RSM_TSK
__tk_rsm_tsk:
#endif

#ifndef	USE_FUNC_TK_FRSM_TSK
__tk_frsm_tsk:
#endif

#ifndef	USE_FUNC_TK_SLP_TSK
__tk_slp_tsk:
__tk_slp_tsk_u:
#endif

#ifndef	USE_FUNC_TK_WUP_TSK
__tk_wup_tsk:
#endif

#ifndef	USE_FUNC_TK_CAN_WUP
__tk_can_wup:
#endif

#ifndef	USE_FUNC_TK_SIG_TEV
__tk_sig_tev:
#endif

#ifndef	USE_FUNC_TK_WAI_TEV
__tk_wai_tev:
__tk_wai_tev_u:
#endif

#ifndef	USE_FUNC_TK_DIS_WAI
__tk_dis_wai:
#endif

#ifndef	USE_FUNC_TK_ENA_WAI
__tk_ena_wai:
#endif

#ifndef	USE_FUNC_TK_CRE_SEM
__tk_cre_sem:
#endif

#ifndef	USE_FUNC_TK_DEL_SEM
__tk_del_sem:
#endif

#ifndef	USE_FUNC_TK_SIG_SEM
__tk_sig_sem:
#endif

#ifndef	USE_FUNC_TK_WAI_SEM
__tk_wai_sem:
#endif

#ifndef	USE_FUNC_TK_REF_SEM
__tk_ref_sem:
#endif

#ifndef	USE_FUNC_TK_CRE_MTX
__tk_cre_mtx:
#endif

#ifndef	USE_FUNC_TK_DEL_MTX
__tk_del_mtx:
#endif

#ifndef	USE_FUNC_TK_LOC_MTX
__tk_loc_mtx:
__tk_loc_mtx_u:
#endif

#ifndef	USE_FUNC_TK_UNL_MTX
__tk_unl_mtx:
#endif

#ifndef	USE_FUNC_TK_REF_MTX
__tk_ref_mtx:
#endif

#ifndef	USE_FUNC_TK_CRE_FLG
__tk_cre_flg:
#endif

#ifndef	USE_FUNC_TK_DEL_FLG
__tk_del_flg:
#endif

#ifndef	USE_FUNC_TK_SET_FLG
__tk_set_flg:
#endif

#ifndef	USE_FUNC_TK_CLR_FLG
__tk_clr_flg:
#endif

#ifndef	USE_FUNC_TK_WAI_FLG
__tk_wai_flg:
#endif

#ifndef	USE_FUNC_TK_REF_FLG
__tk_ref_flg:
#endif

#ifndef	USE_FUNC_TK_CRE_MBX
__tk_cre_mbx:
#endif

#ifndef	USE_FUNC_TK_DEL_MBX
__tk_del_mbx:
#endif

#ifndef	USE_FUNC_TK_SND_MBX
__tk_snd_mbx:
#endif

#ifndef	USE_FUNC_TK_RCV_MBX
__tk_rcv_mbx:
__tk_rcv_mbx_u:
#endif

#ifndef	USE_FUNC_TK_REF_MBX
__tk_ref_mbx:
#endif

#ifndef	USE_FUNC_TK_CRE_MBF
__tk_cre_mbf:
#endif

#ifndef	USE_FUNC_TK_DEL_MBF
__tk_del_mbf:
#endif

#ifndef	USE_FUNC_TK_SND_MBF
__tk_snd_mbf:
__tk_snd_mbf_u:
#endif

#ifndef	USE_FUNC_TK_RCV_MBF
__tk_rcv_mbf:
__tk_rcv_mbf_u:
#endif

#ifndef	USE_FUNC_TK_REF_MBF
__tk_ref_mbf:
#endif

#ifndef	USE_FUNC_TK_CRE_POR
__tk_cre_por:
#endif

#ifndef	USE_FUNC_TK_DEL_POR
__tk_del_por:
#endif

#ifndef	USE_FUNC_TK_CAL_POR
__tk_cal_por:
__tk_cal_por_u:
#endif

#ifndef	USE_FUNC_TK_ACP_POR
__tk_acp_por:
__tk_acp_por_u:
#endif

#ifndef	USE_FUNC_TK_FWD_POR
__tk_fwd_por:
#endif

#ifndef	USE_FUNC_TK_RPL_RDV
__tk_rpl_rdv:
#endif

#ifndef	USE_FUNC_TK_REF_POR
__tk_ref_por:
#endif

#ifndef	USE_FUNC_TK_DEF_INT
__tk_def_int:
#endif

#ifndef	USE_FUNC_TK_RET_INT
__tk_ret_int:
#endif

#ifndef	USE_FUNC_TK_CRE_MPL
__tk_cre_mpl:
#endif

#ifndef	USE_FUNC_TK_DEL_MPL
__tk_del_mpl:
#endif

#ifndef	USE_FUNC_TK_GET_MPL
__tk_get_mpl:
__tk_get_mpl_u:
#endif

#ifndef	USE_FUNC_TK_REL_MPL
__tk_rel_mpl:
#endif

#ifndef	USE_FUNC_TK_REF_MPL
__tk_ref_mpl:
#endif

#ifndef	USE_FUNC_TK_CRE_MPF
__tk_cre_mpf:
#endif

#ifndef	USE_FUNC_TK_DEL_MPF
__tk_del_mpf:
#endif

#ifndef	USE_FUNC_TK_GET_MPF
__tk_get_mpf:
__tk_get_mpf_u:
#endif

#ifndef	USE_FUNC_TK_REL_MPF
__tk_rel_mpf:
#endif

#ifndef	USE_FUNC_TK_REF_MPF
__tk_ref_mpf:
#endif

#ifndef	USE_FUNC_TK_SET_TIM
__tk_set_tim:
__tk_set_tim_u:
#endif

#ifndef	USE_FUNC_TK_GET_TIM
__tk_get_tim:
__tk_get_tim_u:
#endif

#ifndef	USE_FUNC_TK_GET_OTM
__tk_get_otm:
__tk_get_otm_u:
#endif

#ifndef	USE_FUNC_TK_DLY_TSK
__tk_dly_tsk:
__tk_dly_tsk_u:
#endif

#ifndef	USE_FUNC_TK_CRE_CYC
__tk_cre_cyc:
__tk_cre_cyc_u:
#endif

#ifndef	USE_FUNC_TK_DEL_CYC
__tk_del_cyc:
#endif

#ifndef	USE_FUNC_TK_STA_CYC
__tk_sta_cyc:
#endif

#ifndef	USE_FUNC_TK_STP_CYC
__tk_stp_cyc:
#endif

#ifndef	USE_FUNC_TK_REF_CYC
__tk_ref_cyc:
__tk_ref_cyc_u:
#endif

#ifndef	USE_FUNC_TK_CRE_ALM
__tk_cre_alm:
#endif

#ifndef	USE_FUNC_TK_DEL_ALM
__tk_del_alm:
#endif

#ifndef	USE_FUNC_TK_STA_ALM
__tk_sta_alm:
__tk_sta_alm_u:
#endif

#ifndef	USE_FUNC_TK_STP_ALM
__tk_stp_alm:
#endif

#ifndef	USE_FUNC_TK_REF_ALM
__tk_ref_alm:
__tk_ref_alm_u:
#endif

#ifndef	USE_FUNC_TK_REF_VER
__tk_ref_ver:
#endif

#ifndef	USE_FUNC_TK_REF_SYS
__tk_ref_sys:
#endif

#ifndef	USE_FUNC_TK_DEF_SSY
__tk_def_ssy:
#endif

#ifndef	USE_FUNC_TK_STA_SSY
__tk_sta_ssy:
#endif

#ifndef	USE_FUNC_TK_CLN_SSY
__tk_cln_ssy:
#endif

#ifndef	USE_FUNC_TK_EVT_SSY
__tk_evt_ssy:
#endif

#ifndef	USE_FUNC_TK_REF_SSY
__tk_ref_ssy:
#endif

#ifndef	USE_FUNC_TK_CRE_RES
__tk_cre_res:
#endif

#ifndef	USE_FUNC_TK_DEL_RES
__tk_del_res:
#endif

#ifndef	USE_FUNC_TK_GET_RES
__tk_get_res:
#endif

#ifndef	USE_FUNC_TK_SET_POW
__tk_set_pow:
#endif

