/*
 *----------------------------------------------------------------------
 *    T-Kernel 2.0 Software Package
 *
 *    Copyright 2011 by Ken Sakamura.
 *    This software is distributed under the T-License 2.0.
 *----------------------------------------------------------------------
 *
 *    Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
 *
 *----------------------------------------------------------------------
 *    UCT T2AS DevKit tuned for LEON5 Version 1.00.00
 *    Copyright (c) 2021 UC Technology. All Rights Reserved.
 *----------------------------------------------------------------------
 */

/*
 *	@(#)asm.inc
 *
 *	Assembler Macro
 */

#ifndef __TK_ASM_H__
#define	__TK_ASM_H__	1

#include "tk/sysdef.inc"
#include "tk/sysdepend/asm_common.inc"

#endif /* __TK_ASM_H__ */
