#! /usr/local/bin/perl
#
# ----------------------------------------------------------------------
#     T-Kernel 2.0 Software Package
#
#     Copyright 2011 by Ken Sakamura.
#     This software is distributed under the T-License 2.0.
# ----------------------------------------------------------------------
#
#     Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
#
# ----------------------------------------------------------------------
#     Changes: Adapted to the ASP-SH7750R Board.
#     Changed by UC Technology at 2012/12/25.
#     
#     UCT T-Kernel 2.0 DevKit tuned for SH7750R Version 1.00.00
#     Copyright (c) 2012 UC Technology. All Rights Reserved.
# ----------------------------------------------------------------------
#

#	mktdsvc
#
#	T-Kernel/DS system call
#	interface library generation script
#
#

$usage = 'usage: mktdsvc cpu infile';

$infile = "";	# input file

#
# analyze command line parameter
#
$cpu = $ARGV[0];
$infile = $ARGV[1];
if ( $cpu eq "" ) {
	print STDERR "$usage\n";
	exit(1);
}
if ( $infile eq "" ) {
	print STDERR "Too few arguments\n";
	exit(1);
}

#
# parse definition file
#
open(IN, "$infile") || die "can not open $infile\n";

$ignore = 1;
$tb_h = "tdsvctbl.h";
$fn_h = "tdfncd.h";
$tb_inc = "tdsvctbl.inc";
$fn_inc = "tdfncd.inc";
chop($incfile = `basename $infile`);

while ( <IN> ) {

	# skip to definition line
	if ( $ignore != 0 ) {
		$ignore = 0 if ( /^(#|\/\*\*).*\bDEFINE_TDSVC\b/ );
		next;
	}

	chop;
	s/^\s//;	# trim space code

	next if ( /^$/ );	# skip empty line
	next if ( /^#/ );	# skip comment line

	# input data type
	if ( /^(\/\*\s+)*\[/ ) {
		( $inp ) = /\[(.*)\]/;
		next;
	}

	# clear input data type
	if ( /^\*\*/ ) {
		$inp = "";
		next;
	}

	# scan data
	if ( $inp =~ /^(BRANCH TABLE FILE)$/i ) {
		$tb_inc = $_;
	}
	if ( $inp =~ /^(FNUMBER HEADER FILE)$/i ) {
		$fn_inc = $_;
	}
	if ( $inp =~ /^(BEGIN SYSCALLS)$/i ) {
		s/\s+/ /g;	# delete extra space code

		$syscalls[$#syscalls+1] = $_ if ( /^IMPORT/ );

		$syscalls[$#syscalls+1] = "" if ( /RESERVE_NO/ );

		if ( ( $align ) = /ALIGN_NO (0x[0-9a-zA-Z]+|[0-9]+)\b/ ) {
			$align = oct($align) if ( $align =~ /^0/ );
			if ( $align > 0 ) {
				$i = $align - ($#syscalls + 1) % $align;
				if ( $i > 1 && $i < $align ) {
					$syscalls[$#syscalls+$i-1] = "";
				} elsif ( $align > 1 && $#syscalls < 0 ) {
					$syscalls[$align-2] = "";
				}
			}
		}
	}
}

close(IN);

if ( $#syscalls < 0 ) {
	print stderr "There is no definition of a system call.\n";
	exit(1);
}

# ----------------------------------------------------------------------------
#
# generate function code definition file
#
open(FN_H, ">sysdepend/include/$fn_h") || die "can not open sysdepend/include/$fn_h\n";

### create header part ###
print FN_H <<EndOfFnHeader;
/*
 *----------------------------------------------------------------------
 *    T-Kernel 2.0 Software Package
 *
 *    Copyright 2011 by Ken Sakamura.
 *    This software is distributed under the T-License 2.0.
 *----------------------------------------------------------------------
 *
 *    Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
 *
 *----------------------------------------------------------------------
 */

/*
 *	T-Kernel/DS function code
 */

EndOfFnHeader

### create function code ###
for ( $i = 0; $i <= $#syscalls; $i++ ) {
	next if ( $syscalls[$i] eq "" );

	( $Func, $func, $ret, @para ) = &split_func($syscalls[$i]);
	$fno = ((($i + 1) << 16) + (($#para + 1) << 8)) | 0x80000000;
	printf FN_H "#define TDFN_${Func}\t0x%08x\n", $fno;
}
print FN_H "\n";

close(FN_H);

# ----------------------------------------------------------------------------
#
# generate function code definition file
#
open(FN_INC, ">sysdepend/include/$fn_inc") || die "can not open sysdepend/include/$fn_inc\n";

### create header part ###
print FN_INC <<EndOfFnHeader;
;/*
; *----------------------------------------------------------------------
; *    T-Kernel 2.0 Software Package
; *
; *    Copyright 2011 by Ken Sakamura.
; *    This software is distributed under the T-License 2.0.
; *----------------------------------------------------------------------
; *
; *    Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
; *
; *----------------------------------------------------------------------
; *    Changes: Adapted to the ASP-SH7750R Board.
; *    Changed by UC Technology at 2012/12/25.
; *    
; *    UCT T-Kernel 2.0 DevKit tuned for SH7750R Version 1.00.00
; *    Copyright (c) 2012 UC Technology. All Rights Reserved.
; *----------------------------------------------------------------------
; */

;/*
; *	T-Kernel/DS function code [HEW]
; *
; *	   created from $incfile
; */

EndOfFnHeader

### create function code ###
for ( $i = 0; $i <= $#syscalls; $i++ ) {
	next if ( $syscalls[$i] eq "" );

	( $Func, $func, $ret, @para ) = &split_func($syscalls[$i]);
	$fno = ((($i + 1) << 16) + (($#para + 1) << 8)) | 0x80000000;
	printf FN_INC "TDFN_${Func}:\t.define\t\"H'%08x\"\n", $fno;
}
print FN_INC "\n";

close(FN_INC);

# ----------------------------------------------------------------------------
#
# generate branch table
#
open(TB_H, ">sysdepend/include/$tb_h") || die "can not open sysdepend/include/$tb_h\n";

### create header part ###
print TB_H <<EndOfTbHeader;
/*
 *----------------------------------------------------------------------
 *    T-Kernel 2.0 Software Package
 *
 *    Copyright 2011 by Ken Sakamura.
 *    This software is distributed under the T-License 2.0.
 *----------------------------------------------------------------------
 *
 *    Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
 *
 *----------------------------------------------------------------------
 */

/*
 *	T-Kernel/DS system call branch table
 *
 */

#include <machine.h>

#define _TDSC_ENTRY(name)	.int	Csym(_##name)

EndOfTbHeader

# number of system call
printf TB_H "#define N_TDFN	%d\n", $#syscalls + 1;
printf TB_H "\n";

### create branch table ###
for ( $i = 0; $i <= $#syscalls; $i++ ) {
	if ( $syscalls[$i] eq "" ) {
		printf TB_H "\t_TDSC_ENTRY(no_support)\n";
	} else {
		( $Func, $func, $ret, @para ) = &split_func($syscalls[$i]);
		print TB_H "\t_TDSC_ENTRY(${func})\n";
	}
}

close(TB_H);

# ----------------------------------------------------------------------------
#
# generate branch table
#
open(TB_INC, ">sysdepend/include/$tb_inc") || die "can not open sysdepend/include/$tb_inc\n";

### create header part ###
print TB_INC <<EndOfTbHeader;
;/*
; *----------------------------------------------------------------------
; *    T-Kernel 2.0 Software Package
; *
; *    Copyright 2011 by Ken Sakamura.
; *    This software is distributed under the T-License 2.0.
; *----------------------------------------------------------------------
; *
; *    Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
; *
; *----------------------------------------------------------------------
; *    Changes: Adapted to the ASP-SH7750R Board.
; *    Changed by UC Technology at 2012/12/25.
; *    
; *    UCT T-Kernel 2.0 DevKit tuned for SH7750R Version 1.00.00
; *    Copyright (c) 2012 UC Technology. All Rights Reserved.
; *----------------------------------------------------------------------
; */

;/*
; *	T-Kernel/DS system call branch table [HEW]
; *
; *	   created from $incfile
; */

	.include "machine.inc"

	.macro _TDSC_ENTRY name
	.aif	"\\name" NE "_no_support"	;; avoid 801 (W) MULTIPLE SYMBOLS
	.import	\\name
	.aendi
	.data.l	\\name
	.endm

EndOfTbHeader

# number of system call
printf TB_INC "N_TDFN:\t.equ\t%d\n", $#syscalls + 1;
printf TB_INC "\n";

### create branch table ###
for ( $i = 0; $i <= $#syscalls; $i++ ) {
	if ( $syscalls[$i] eq "" ) {
		printf TB_INC "\t_TDSC_ENTRY\t_no_support\n";
	} else {
		( $Func, $func, $ret, @para ) = &split_func($syscalls[$i]);
		print TB_INC "\t_TDSC_ENTRY\t__${func}\n";
	}
}

close(TB_INC);

# ----------------------------------------------------------------------------
#
# create SVC interface function
#

for ( $i = 0; $i <= $#syscalls; $i++ ) {
	next if ( $syscalls[$i] eq "" );

	$syscall = $syscalls[$i];
	( $Func, $func, $ret, @para ) = &split_func($syscall);

	$fname = $func;
	$fname =~ tr/A-Z/a-z/;	# to lower case

	# open library source file
	open(LIB, ">sysdepend/$cpu/$fname.S") || die "can not open sysdepend/$cpu/$fname.S\n";

	print LIB <<EndOfIfLibHeader;
;/*
; *----------------------------------------------------------------------
; *    T-Kernel 2.0 Software Package
; *
; *    Copyright 2011 by Ken Sakamura.
; *    This software is distributed under the T-License 2.0.
; *----------------------------------------------------------------------
; *
; *    Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
; *
; *----------------------------------------------------------------------
; *    Changes: Adapted to the ASP-SH7750R Board.
; *    Changed by UC Technology at 2012/12/25.
; *    
; *    UCT T-Kernel 2.0 DevKit tuned for SH7750R Version 1.00.00
; *    Copyright (c) 2012 UC Technology. All Rights Reserved.
; *----------------------------------------------------------------------
; */

;/*
; *	T-Kernel/DS SVC interface library ($cpu) [HEW]
; *
; *	   created from $incfile
; */

EndOfIfLibHeader

	# system dependencies
	require("../build_src/$cpu/makeiftd.pl");
	&makelib();

	close(LIB);
}

exit(0);

# ============================================================================

#
# split definition of function
#
sub split_func
{
	local($syscall) = @_;
	local($Func, $func, $ret, @para, $p);

	( $ret, $func, $p ) =
		( $syscall =~ /IMPORT\s+(\w+)\s+(\w+)\s*\((.*)\)\s*;/ );

	$p =~ s/^\s*//;		# trim space code
	$p =~ s/\s*$//;

	@para = split(/\s*,\s*/, $p);	# split parameters

	if ( $#para == 0 && $para[0] =~ /^void$/i ) {
		# no params (void)
		@para = ();
	}

	if ( $ret =~ /^void$/i ) {
		# return type is "void"
		$ret = "";
	}

	$Func = $func;
	$Func =~ s/^td_//;	# delete "td_"
	$Func =~ tr/a-z/A-Z/;	# to upper case

	return ( $Func, $func, $ret, @para );
}
